import type {
  ListeningExercise,
  ListeningExerciseMap,
  ListeningLesson,
  ListeningExerciseType,
  ListeningTopic,
  SupportedListeningLanguageCode,
} from "./types";

type ExerciseSeed = Omit<ListeningExercise, "languageCode">;

function createExercises(languageCode: SupportedListeningLanguageCode, items: ExerciseSeed[]): ListeningExercise[] {
  return items.map((item) => ({
    ...item,
    languageCode,
  }));
}

function makeId(prefix: string, languageCode: SupportedListeningLanguageCode, index: number) {
  return `${languageCode}-${prefix}-${index}`;
}

export const listeningExercisesByLanguage: ListeningExerciseMap = {
  zh: createExercises("zh", [
    {
      id: makeId("ac", "zh", 1),
      type: "audio_choice",
      question: "Người nói đang đi đâu?",
      mediaUrl: "/audio/zh/ac_1.mp3",
      transcript: "我今天要去图书馆看书。",
      answer: "B. 我去图书馆",
      options: ["A. 我去学校", "B. 我去图书馆", "C. 我去公司", "D. 我去医院"],
      difficulty: "Cơ bản",
      explanation: "Từ khóa: 图书馆 = thư viện.",
    },
    {
      id: makeId("ac", "zh", 2),
      type: "audio_choice",
      question: "Người nói muốn uống gì?",
      mediaUrl: "/audio/zh/ac_2.mp3",
      transcript: "天气太热了，我想喝一杯冰茶。",
      answer: "C. 冰茶",
      options: ["A. 牛奶", "B. 咖啡", "C. 冰茶", "D. 果汁"],
      difficulty: "Cơ bản",
      explanation: "冰茶 la tra da.",
    },
    {
      id: makeId("ac", "zh", 3),
      type: "audio_choice",
      question: "Người nói sẽ làm gì vào cuối tuần?",
      mediaUrl: "/audio/zh/ac_3.mp3",
      transcript: "这个周末我要和朋友一起去看电影。",
      answer: "A. 去看电影",
      options: ["A. 去看电影", "B. 去爬山", "C. 去上课", "D. 去买菜"],
      difficulty: "Trung cấp",
      explanation: "看电影 = xem phim.",
    },
    {
      id: makeId("ac", "zh", 4),
      type: "audio_choice",
      question: "Người nói nghĩ rằng môn học nào khó nhất?",
      mediaUrl: "/audio/zh/ac_4.mp3",
      transcript: "我觉得汉字最难，但是也很有意思。",
      answer: "D. 汉字",
      options: ["A. 发音", "B. 语法", "C. 听力", "D. 汉字"],
      difficulty: "Nâng cao",
      explanation: "最难 = kho nhat.",
    },
    {
      id: makeId("aw", "zh", 1),
      type: "audio_write",
      question: "Nghe va viet lai cau vua nghe:",
      mediaUrl: "/audio/zh/aw_1.mp3",
      transcript: "今天天气很好，我想出去散步。",
      answer: "今天天气很好，我想出去散步。",
      hints: ["今天", "天气", "很好", "我", "想", "出去", "散步"],
      difficulty: "Trung cấp",
      explanation: "散步 nghia la di dao.",
    },
    {
      id: makeId("aw", "zh", 2),
      type: "audio_write",
      question: "Nghe va viet lai cau vua nghe:",
      mediaUrl: "/audio/zh/aw_2.mp3",
      transcript: "我每天晚上练习中文听力。",
      answer: "我每天晚上练习中文听力。",
      hints: ["我", "每天晚上", "练习", "中文", "听力"],
      difficulty: "Cơ bản",
      explanation: "听力 là kỹ năng nghe.",
    },
    {
      id: makeId("aw", "zh", 3),
      type: "audio_write",
      question: "Nghe va viet lai cau vua nghe:",
      mediaUrl: "/audio/zh/aw_3.mp3",
      transcript: "明天早上我们要去机场接老师。",
      answer: "明天早上我们要去机场接老师。",
      hints: ["明天早上", "我们", "要", "去", "机场", "接", "老师"],
      difficulty: "Trung cấp",
      explanation: "机场 la san bay, 接老师 la don thay co.",
    },
    {
      id: makeId("aw", "zh", 4),
      type: "audio_write",
      question: "Nghe va viet lai cau vua nghe:",
      mediaUrl: "/audio/zh/aw_4.mp3",
      transcript: "如果有时间，我想给妈妈买一份礼物。",
      answer: "如果有时间，我想给妈妈买一份礼物。",
      hints: ["如果", "有时间", "我", "想", "给", "妈妈", "买", "礼物"],
      difficulty: "Nâng cao",
      explanation: "礼物 = qua tang.",
    },
    {
      id: makeId("vc", "zh", 1),
      type: "video_choice",
      question: "Người trong video đang nói về chủ đề gì?",
      mediaUrl: "/video/zh/vc_1.mp4",
      transcript: "大家好，今天我来介绍我的家庭。",
      answer: "B. 家庭",
      options: ["A. 天气", "B. 家庭", "C. 工作", "D. 旅游"],
      difficulty: "Cơ bản",
      explanation: "介绍我的家庭 = giới thiệu gia đình tôi.",
    },
    {
      id: makeId("vc", "zh", 2),
      type: "video_choice",
      question: "Người nói đang giới thiệu điều gì?",
      mediaUrl: "/video/zh/vc_2.mp4",
      transcript: "我想分享一下我在大学的一天。",
      answer: "C. Cuoc song o truong dai hoc",
      options: ["A. Mot chuyen du lich", "B. Cong viec ban thoi gian", "C. Cuoc song o truong dai hoc", "D. Cach nau an"],
      difficulty: "Trung cấp",
      explanation: "大学的一天 = mot ngay o dai hoc.",
    },
    {
      id: makeId("vc", "zh", 3),
      type: "video_choice",
      question: "Người nói sắp làm gì trong kỳ nghỉ?",
      mediaUrl: "/video/zh/vc_3.mp4",
      transcript: "下个月我打算去北京旅游，还想拍很多照片。",
      answer: "A. 去北京旅游",
      options: ["A. 去北京旅游", "B. 去上海工作", "C. 在家休息", "D. 学开车"],
      difficulty: "Trung cấp",
      explanation: "打算 = du dinh.",
    },
    {
      id: makeId("vc", "zh", 4),
      type: "video_choice",
      question: "Video đang nói về kỹ năng nào?",
      mediaUrl: "/video/zh/vc_4.mp4",
      transcript: "今天我教大家怎么做西红柿炒鸡蛋。",
      answer: "D. Nau an",
      options: ["A. Hoc bai", "B. Mua sam", "C. Tap the duc", "D. Nau an"],
      difficulty: "Cơ bản",
      explanation: "西红柿炒鸡蛋 là món cà chua xào trứng.",
    },
  ]),
  en: createExercises("en", [
    {
      id: makeId("ac", "en", 1),
      type: "audio_choice",
      question: "Người nói đang đi đâu?",
      mediaUrl: "/audio/en/ac_1.mp3",
      transcript: "I am going to the library after class.",
      answer: "B. The library",
      options: ["A. The school office", "B. The library", "C. The company", "D. The hospital"],
      difficulty: "Cơ bản",
      explanation: "Library là thư viện.",
    },
    {
      id: makeId("ac", "en", 2),
      type: "audio_choice",
      question: "Người nói muốn uống gì?",
      mediaUrl: "/audio/en/ac_2.mp3",
      transcript: "It is so hot, I want a glass of iced tea.",
      answer: "C. Iced tea",
      options: ["A. Milk", "B. Coffee", "C. Iced tea", "D. Juice"],
      difficulty: "Cơ bản",
      explanation: "Iced tea la tra da.",
    },
    {
      id: makeId("ac", "en", 3),
      type: "audio_choice",
      question: "Người nói sẽ làm gì vào cuối tuần?",
      mediaUrl: "/audio/en/ac_3.mp3",
      transcript: "This weekend I am going to watch a movie with my friends.",
      answer: "A. Watch a movie",
      options: ["A. Watch a movie", "B. Go hiking", "C. Attend class", "D. Buy groceries"],
      difficulty: "Trung cấp",
      explanation: "Watch a movie = di xem phim.",
    },
    {
      id: makeId("ac", "en", 4),
      type: "audio_choice",
      question: "Người nói thấy phần nào khó nhất?",
      mediaUrl: "/audio/en/ac_4.mp3",
      transcript: "I think pronunciation is the hardest part, but it is interesting.",
      answer: "A. Pronunciation",
      options: ["A. Pronunciation", "B. Grammar", "C. Listening", "D. Vocabulary"],
      difficulty: "Nâng cao",
      explanation: "The hardest part = phan kho nhat.",
    },
    {
      id: makeId("aw", "en", 1),
      type: "audio_write",
      question: "Nghe va viet lai cau vua nghe:",
      mediaUrl: "/audio/en/aw_1.mp3",
      transcript: "The weather is nice today, so I want to take a walk.",
      answer: "The weather is nice today, so I want to take a walk.",
      hints: ["The weather", "is nice", "today", "I want", "to take", "a walk"],
      difficulty: "Trung cấp",
      explanation: "Take a walk = di dao.",
    },
    {
      id: makeId("aw", "en", 2),
      type: "audio_write",
      question: "Nghe va viet lai cau vua nghe:",
      mediaUrl: "/audio/en/aw_2.mp3",
      transcript: "I practice English listening every evening.",
      answer: "I practice English listening every evening.",
      hints: ["I", "practice", "English listening", "every evening"],
      difficulty: "Cơ bản",
      explanation: "Every evening = mỗi tối.",
    },
    {
      id: makeId("aw", "en", 3),
      type: "audio_write",
      question: "Nghe va viet lai cau vua nghe:",
      mediaUrl: "/audio/en/aw_3.mp3",
      transcript: "Tomorrow morning we will go to the airport to meet our teacher.",
      answer: "Tomorrow morning we will go to the airport to meet our teacher.",
      hints: ["Tomorrow morning", "we will go", "to the airport", "to meet", "our teacher"],
      difficulty: "Trung cấp",
      explanation: "Meet our teacher o day la di don thay co.",
    },
    {
      id: makeId("aw", "en", 4),
      type: "audio_write",
      question: "Nghe va viet lai cau vua nghe:",
      mediaUrl: "/audio/en/aw_4.mp3",
      transcript: "If I have time, I want to buy a gift for my mother.",
      answer: "If I have time, I want to buy a gift for my mother.",
      hints: ["If I have time", "I want", "to buy", "a gift", "for my mother"],
      difficulty: "Nâng cao",
      explanation: "Câu điều kiện bắt đầu bằng If I have time.",
    },
    {
      id: makeId("vc", "en", 1),
      type: "video_choice",
      question: "Người trong video đang nói về chủ đề gì?",
      mediaUrl: "/video/en/vc_1.mp4",
      transcript: "Hello everyone, today I want to introduce my family.",
      answer: "B. Family",
      options: ["A. Weather", "B. Family", "C. Work", "D. Travel"],
      difficulty: "Cơ bản",
      explanation: "Introduce my family = giới thiệu gia đình.",
    },
    {
      id: makeId("vc", "en", 2),
      type: "video_choice",
      question: "Người nói đang kể về điều gì?",
      mediaUrl: "/video/en/vc_2.mp4",
      transcript: "Let me share a normal day at my university.",
      answer: "C. University life",
      options: ["A. A trip", "B. A part-time job", "C. University life", "D. Cooking tips"],
      difficulty: "Trung cấp",
      explanation: "A normal day at my university = mot ngay o truong dai hoc.",
    },
    {
      id: makeId("vc", "en", 3),
      type: "video_choice",
      question: "Người nói sắp làm gì vào kỳ nghỉ?",
      mediaUrl: "/video/en/vc_3.mp4",
      transcript: "Next month I am planning to travel to Berlin and take many photos.",
      answer: "A. Travel to Berlin",
      options: ["A. Travel to Berlin", "B. Work in Munich", "C. Stay home", "D. Learn to drive"],
      difficulty: "Trung cấp",
      explanation: "Planning to travel = du dinh di du lich.",
    },
    {
      id: makeId("vc", "en", 4),
      type: "video_choice",
      question: "Video đang nói về kỹ năng nào?",
      mediaUrl: "/video/en/vc_4.mp4",
      transcript: "Today I will show you how to make tomato egg soup.",
      answer: "D. Cooking",
      options: ["A. Studying", "B. Shopping", "C. Exercising", "D. Cooking"],
      difficulty: "Cơ bản",
      explanation: "Show you how to make ... là dạng hướng dẫn nấu ăn.",
    },
  ]),
  ja: createExercises("ja", [
    {
      id: makeId("ac", "ja", 1),
      type: "audio_choice",
      question: "Người nói đang đi đâu?",
      mediaUrl: "/audio/ja/ac_1.mp3",
      transcript: "授業の後で図書館へ行きます。",
      answer: "B. 図書館",
      options: ["A. 学校の事務室", "B. 図書館", "C. 会社", "D. 病院"],
      difficulty: "Cơ bản",
      explanation: "図書館 = thư viện.",
    },
    {
      id: makeId("ac", "ja", 2),
      type: "audio_choice",
      question: "Người nói muốn uống gì?",
      mediaUrl: "/audio/ja/ac_2.mp3",
      transcript: "暑いので、冷たいお茶を飲みたいです。",
      answer: "C. 冷たいお茶",
      options: ["A. 牛乳", "B. コーヒー", "C. 冷たいお茶", "D. ジュース"],
      difficulty: "Cơ bản",
      explanation: "冷たいお茶 = tra lanh.",
    },
    {
      id: makeId("ac", "ja", 3),
      type: "audio_choice",
      question: "Người nói sẽ làm gì vào cuối tuần?",
      mediaUrl: "/audio/ja/ac_3.mp3",
      transcript: "週末は友だちと映画を見に行きます。",
      answer: "A. 映画を見に行く",
      options: ["A. 映画を見に行く", "B. 山に登る", "C. 授業を受ける", "D. 買い物をする"],
      difficulty: "Trung cấp",
      explanation: "映画を見に行く = di xem phim.",
    },
    {
      id: makeId("ac", "ja", 4),
      type: "audio_choice",
      question: "Người nói thấy phần nào khó nhất?",
      mediaUrl: "/audio/ja/ac_4.mp3",
      transcript: "漢字が一番難しいですが、とても面白いです。",
      answer: "D. 漢字",
      options: ["A. 発音", "B. 文法", "C. 聞き取り", "D. 漢字"],
      difficulty: "Nâng cao",
      explanation: "一番難しい = kho nhat.",
    },
    {
      id: makeId("aw", "ja", 1),
      type: "audio_write",
      question: "Nghe va viet lai cau vua nghe:",
      mediaUrl: "/audio/ja/aw_1.mp3",
      transcript: "今日は天気がいいので、散歩したいです。",
      answer: "今日は天気がいいので、散歩したいです。",
      hints: ["今日", "天気", "いい", "散歩", "したい"],
      difficulty: "Trung cấp",
      explanation: "散歩したいです = muon di dao.",
    },
    {
      id: makeId("aw", "ja", 2),
      type: "audio_write",
      question: "Nghe va viet lai cau vua nghe:",
      mediaUrl: "/audio/ja/aw_2.mp3",
      transcript: "私は毎晩日本語の聞き取りを練習します。",
      answer: "私は毎晩日本語の聞き取りを練習します。",
      hints: ["私", "毎晩", "日本語", "聞き取り", "練習"],
      difficulty: "Cơ bản",
      explanation: "聞き取り = nghe hieu / listening.",
    },
    {
      id: makeId("aw", "ja", 3),
      type: "audio_write",
      question: "Nghe va viet lai cau vua nghe:",
      mediaUrl: "/audio/ja/aw_3.mp3",
      transcript: "明日の朝、空港へ先生を迎えに行きます。",
      answer: "明日の朝、空港へ先生を迎えに行きます。",
      hints: ["明日の朝", "空港", "先生", "迎えに", "行きます"],
      difficulty: "Trung cấp",
      explanation: "迎えに行きます = di don ai.",
    },
    {
      id: makeId("aw", "ja", 4),
      type: "audio_write",
      question: "Nghe va viet lai cau vua nghe:",
      mediaUrl: "/audio/ja/aw_4.mp3",
      transcript: "時間があれば、母にプレゼントを買いたいです。",
      answer: "時間があれば、母にプレゼントを買いたいです。",
      hints: ["時間", "あれば", "母", "プレゼント", "買いたい"],
      difficulty: "Nâng cao",
      explanation: "〜あれば là cấu trúc điều kiện.",
    },
    {
      id: makeId("vc", "ja", 1),
      type: "video_choice",
      question: "Người trong video đang nói về chủ đề gì?",
      mediaUrl: "/video/ja/vc_1.mp4",
      transcript: "みなさん、今日は私の家族を紹介します。",
      answer: "B. 家族",
      options: ["A. 天気", "B. 家族", "C. 仕事", "D. 旅行"],
      difficulty: "Cơ bản",
      explanation: "家族を紹介します = giới thiệu gia đình.",
    },
    {
      id: makeId("vc", "ja", 2),
      type: "video_choice",
      question: "Người nói đang kể về điều gì?",
      mediaUrl: "/video/ja/vc_2.mp4",
      transcript: "大学での一日を皆さんに紹介したいです。",
      answer: "C. Daigaku no seikatsu",
      options: ["A. 旅行", "B. アルバイト", "C. 大学の生活", "D. 料理"],
      difficulty: "Trung cấp",
      explanation: "大学での一日 = mot ngay o dai hoc.",
    },
    {
      id: makeId("vc", "ja", 3),
      type: "video_choice",
      question: "Người nói sắp làm gì vào kỳ nghỉ?",
      mediaUrl: "/video/ja/vc_3.mp4",
      transcript: "来月は大阪へ旅行して、たくさん写真を撮りたいです。",
      answer: "A. 大阪へ旅行する",
      options: ["A. 大阪へ旅行する", "B. 東京で働く", "C. 家にいる", "D. 車を習う"],
      difficulty: "Trung cấp",
      explanation: "旅行する = di du lich.",
    },
    {
      id: makeId("vc", "ja", 4),
      type: "video_choice",
      question: "Video đang nói về kỹ năng nào?",
      mediaUrl: "/video/ja/vc_4.mp4",
      transcript: "今日はトマト卵スープの作り方を説明します。",
      answer: "D. 料理",
      options: ["A. 勉強", "B. 買い物", "C. 運動", "D. 料理"],
      difficulty: "Cơ bản",
      explanation: "作り方を説明します = huong dan cach nau.",
    },
  ]),
  ko: createExercises("ko", [
    {
      id: makeId("ac", "ko", 1),
      type: "audio_choice",
      question: "Người nói đang đi đâu?",
      mediaUrl: "/audio/ko/ac_1.mp3",
      transcript: "수업이 끝나면 도서관에 갈 거예요.",
      answer: "B. 도서관",
      options: ["A. 학교 사무실", "B. 도서관", "C. 회사", "D. 병원"],
      difficulty: "Cơ bản",
      explanation: "도서관 = thư viện.",
    },
    {
      id: makeId("ac", "ko", 2),
      type: "audio_choice",
      question: "Người nói muốn uống gì?",
      mediaUrl: "/audio/ko/ac_2.mp3",
      transcript: "너무 더워서 아이스티를 마시고 싶어요.",
      answer: "C. 아이스티",
      options: ["A. 우유", "B. 커피", "C. 아이스티", "D. 주스"],
      difficulty: "Cơ bản",
      explanation: "아이스티 = tra da.",
    },
    {
      id: makeId("ac", "ko", 3),
      type: "audio_choice",
      question: "Người nói sẽ làm gì vào cuối tuần?",
      mediaUrl: "/audio/ko/ac_3.mp3",
      transcript: "주말에 친구와 같이 영화를 보러 갈 거예요.",
      answer: "A. 영화를 보러 가요",
      options: ["A. 영화를 보러 가요", "B. 등산해요", "C. 수업을 들어요", "D. 장을 봐요"],
      difficulty: "Trung cấp",
      explanation: "영화를 보러 가다 = di xem phim.",
    },
    {
      id: makeId("ac", "ko", 4),
      type: "audio_choice",
      question: "Người nói thấy phần nào khó nhất?",
      mediaUrl: "/audio/ko/ac_4.mp3",
      transcript: "저는 발음이 가장 어렵지만 재미있다고 생각해요.",
      answer: "A. 발음",
      options: ["A. 발음", "B. 문법", "C. 듣기", "D. 어휘"],
      difficulty: "Nâng cao",
      explanation: "가장 어렵다 = kho nhat.",
    },
    {
      id: makeId("aw", "ko", 1),
      type: "audio_write",
      question: "Nghe va viet lai cau vua nghe:",
      mediaUrl: "/audio/ko/aw_1.mp3",
      transcript: "오늘은 날씨가 좋아서 산책하고 싶어요.",
      answer: "오늘은 날씨가 좋아서 산책하고 싶어요.",
      hints: ["오늘", "날씨", "좋아서", "산책", "싶어요"],
      difficulty: "Trung cấp",
      explanation: "산책하고 싶어요 = muon di dao.",
    },
    {
      id: makeId("aw", "ko", 2),
      type: "audio_write",
      question: "Nghe va viet lai cau vua nghe:",
      mediaUrl: "/audio/ko/aw_2.mp3",
      transcript: "저는 매일 저녁 한국어 듣기를 연습해요.",
      answer: "저는 매일 저녁 한국어 듣기를 연습해요.",
      hints: ["저는", "매일 저녁", "한국어", "듣기", "연습해요"],
      difficulty: "Cơ bản",
      explanation: "듣기 = kỹ năng nghe.",
    },
    {
      id: makeId("aw", "ko", 3),
      type: "audio_write",
      question: "Nghe va viet lai cau vua nghe:",
      mediaUrl: "/audio/ko/aw_3.mp3",
      transcript: "내일 아침에 공항에서 선생님을 맞이할 거예요.",
      answer: "내일 아침에 공항에서 선생님을 맞이할 거예요.",
      hints: ["내일 아침", "공항", "선생님", "맞이할 거예요"],
      difficulty: "Trung cấp",
      explanation: "맞이하다 = don ai.",
    },
    {
      id: makeId("aw", "ko", 4),
      type: "audio_write",
      question: "Nghe va viet lai cau vua nghe:",
      mediaUrl: "/audio/ko/aw_4.mp3",
      transcript: "시간이 있으면 어머니께 선물을 사고 싶어요.",
      answer: "시간이 있으면 어머니께 선물을 사고 싶어요.",
      hints: ["시간", "있으면", "어머니", "선물", "사고 싶어요"],
      difficulty: "Nâng cao",
      explanation: "-으면 là cấu trúc nếu / if.",
    },
    {
      id: makeId("vc", "ko", 1),
      type: "video_choice",
      question: "Người trong video đang nói về chủ đề gì?",
      mediaUrl: "/video/ko/vc_1.mp4",
      transcript: "여러분, 오늘은 제 가족을 소개할게요.",
      answer: "B. 가족",
      options: ["A. 날씨", "B. 가족", "C. 일", "D. 여행"],
      difficulty: "Cơ bản",
      explanation: "가족을 소개하다 = giới thiệu gia đình.",
    },
    {
      id: makeId("vc", "ko", 2),
      type: "video_choice",
      question: "Người nói đang kể về điều gì?",
      mediaUrl: "/video/ko/vc_2.mp4",
      transcript: "대학교에서 보내는 하루를 소개하고 싶어요.",
      answer: "C. 대학 생활",
      options: ["A. 여행", "B. 아르바이트", "C. 대학 생활", "D. 요리"],
      difficulty: "Trung cấp",
      explanation: "대학 생활 = doi song dai hoc.",
    },
    {
      id: makeId("vc", "ko", 3),
      type: "video_choice",
      question: "Người nói sắp làm gì vào kỳ nghỉ?",
      mediaUrl: "/video/ko/vc_3.mp4",
      transcript: "다음 달에는 부산으로 여행 가서 사진을 많이 찍고 싶어요.",
      answer: "A. 부산으로 여행 가요",
      options: ["A. 부산으로 여행 가요", "B. 서울에서 일해요", "C. 집에 있어요", "D. 운전을 배워요"],
      difficulty: "Trung cấp",
      explanation: "여행 가다 = di du lich.",
    },
    {
      id: makeId("vc", "ko", 4),
      type: "video_choice",
      question: "Video đang nói về kỹ năng nào?",
      mediaUrl: "/video/ko/vc_4.mp4",
      transcript: "오늘은 토마토 달걀 수프 만드는 법을 보여 드릴게요.",
      answer: "D. 요리",
      options: ["A. 공부", "B. 쇼핑", "C. 운동", "D. 요리"],
      difficulty: "Cơ bản",
      explanation: "만드는 법 = cach lam / cach nau.",
    },
  ]),
  de: createExercises("de", [
    {
      id: makeId("ac", "de", 1),
      type: "audio_choice",
      question: "Người nói đang đi đâu?",
      mediaUrl: "/audio/de/ac_1.mp3",
      transcript: "Nach dem Unterricht gehe ich in die Bibliothek.",
      answer: "B. In die Bibliothek",
      options: ["A. Ins Schulburo", "B. In die Bibliothek", "C. Zur Firma", "D. Ins Krankenhaus"],
      difficulty: "Cơ bản",
      explanation: "Bibliothek = thư viện.",
    },
    {
      id: makeId("ac", "de", 2),
      type: "audio_choice",
      question: "Người nói muốn uống gì?",
      mediaUrl: "/audio/de/ac_2.mp3",
      transcript: "Es ist sehr heiß, ich mochte einen Eistee trinken.",
      answer: "C. Eistee",
      options: ["A. Milch", "B. Kaffee", "C. Eistee", "D. Saft"],
      difficulty: "Cơ bản",
      explanation: "Eistee = tra da.",
    },
    {
      id: makeId("ac", "de", 3),
      type: "audio_choice",
      question: "Người nói sẽ làm gì vào cuối tuần?",
      mediaUrl: "/audio/de/ac_3.mp3",
      transcript: "Am Wochenende gehe ich mit Freunden ins Kino.",
      answer: "A. Ins Kino gehen",
      options: ["A. Ins Kino gehen", "B. Wandern gehen", "C. Zum Unterricht gehen", "D. Einkaufen"],
      difficulty: "Trung cấp",
      explanation: "Ins Kino gehen = di xem phim.",
    },
    {
      id: makeId("ac", "de", 4),
      type: "audio_choice",
      question: "Người nói thấy phần nào khó nhất?",
      mediaUrl: "/audio/de/ac_4.mp3",
      transcript: "Ich finde die Aussprache am schwierigsten, aber auch sehr interessant.",
      answer: "A. Aussprache",
      options: ["A. Aussprache", "B. Grammatik", "C. Horen", "D. Wortschatz"],
      difficulty: "Nâng cao",
      explanation: "Am schwierigsten = kho nhat.",
    },
    {
      id: makeId("aw", "de", 1),
      type: "audio_write",
      question: "Nghe va viet lai cau vua nghe:",
      mediaUrl: "/audio/de/aw_1.mp3",
      transcript: "Heute ist das Wetter sehr schon, deshalb mochte ich spazieren gehen.",
      answer: "Heute ist das Wetter sehr schon, deshalb mochte ich spazieren gehen.",
      hints: ["Heute", "Wetter", "sehr schon", "deshalb", "spazieren gehen"],
      difficulty: "Trung cấp",
      explanation: "Spazieren gehen = di dao.",
    },
    {
      id: makeId("aw", "de", 2),
      type: "audio_write",
      question: "Nghe va viet lai cau vua nghe:",
      mediaUrl: "/audio/de/aw_2.mp3",
      transcript: "Ich ube jeden Abend deutsches Horverstehen.",
      answer: "Ich ube jeden Abend deutsches Horverstehen.",
      hints: ["Ich", "ube", "jeden Abend", "deutsches", "Horverstehen"],
      difficulty: "Cơ bản",
      explanation: "Horverstehen = kỹ năng nghe.",
    },
    {
      id: makeId("aw", "de", 3),
      type: "audio_write",
      question: "Nghe va viet lai cau vua nghe:",
      mediaUrl: "/audio/de/aw_3.mp3",
      transcript: "Morgen fruh fahren wir zum Flughafen, um unseren Lehrer abzuholen.",
      answer: "Morgen fruh fahren wir zum Flughafen, um unseren Lehrer abzuholen.",
      hints: ["Morgen fruh", "zum Flughafen", "unseren Lehrer", "abzuholen"],
      difficulty: "Trung cấp",
      explanation: "Abholen = don ai.",
    },
    {
      id: makeId("aw", "de", 4),
      type: "audio_write",
      question: "Nghe va viet lai cau vua nghe:",
      mediaUrl: "/audio/de/aw_4.mp3",
      transcript: "Wenn ich Zeit habe, mochte ich ein Geschenk fur meine Mutter kaufen.",
      answer: "Wenn ich Zeit habe, mochte ich ein Geschenk fur meine Mutter kaufen.",
      hints: ["Wenn ich Zeit habe", "mochte ich", "ein Geschenk", "fur meine Mutter", "kaufen"],
      difficulty: "Nâng cao",
      explanation: "Wenn ... là mệnh đề điều kiện.",
    },
    {
      id: makeId("vc", "de", 1),
      type: "video_choice",
      question: "Người trong video đang nói về chủ đề gì?",
      mediaUrl: "/video/de/vc_1.mp4",
      transcript: "Hallo zusammen, heute mochte ich meine Familie vorstellen.",
      answer: "B. Familie",
      options: ["A. Wetter", "B. Familie", "C. Arbeit", "D. Reisen"],
      difficulty: "Cơ bản",
      explanation: "Meine Familie vorstellen = giới thiệu gia đình.",
    },
    {
      id: makeId("vc", "de", 2),
      type: "video_choice",
      question: "Người nói đang kể về điều gì?",
      mediaUrl: "/video/de/vc_2.mp4",
      transcript: "Ich mochte euch einen typischen Tag an der Universitat zeigen.",
      answer: "C. Uni-Leben",
      options: ["A. Eine Reise", "B. Ein Nebenjob", "C. Uni-Leben", "D. Kochen"],
      difficulty: "Trung cấp",
      explanation: "Typischer Tag an der Universitat = mot ngay o dai hoc.",
    },
    {
      id: makeId("vc", "de", 3),
      type: "video_choice",
      question: "Người nói sắp làm gì vào kỳ nghỉ?",
      mediaUrl: "/video/de/vc_3.mp4",
      transcript: "Nächsten Monat will ich nach Wien reisen und viele Fotos machen.",
      answer: "A. Nach Wien reisen",
      options: ["A. Nach Wien reisen", "B. In Berlin arbeiten", "C. Zu Hause bleiben", "D. Autofahren lernen"],
      difficulty: "Trung cấp",
      explanation: "Reisen = di du lich.",
    },
    {
      id: makeId("vc", "de", 4),
      type: "video_choice",
      question: "Video đang nói về kỹ năng nào?",
      mediaUrl: "/video/de/vc_4.mp4",
      transcript: "Heute zeige ich euch, wie man Tomaten-Ei-Suppe kocht.",
      answer: "D. Kochen",
      options: ["A. Lernen", "B. Einkaufen", "C. Sport", "D. Kochen"],
      difficulty: "Cơ bản",
      explanation: "Wie man ... kocht = cach nau mon gi.",
    },
  ]),
};

export function getListeningExercisesByLanguage(languageCode: string | undefined): ListeningExercise[] {
  if (!languageCode || !(languageCode in listeningExercisesByLanguage)) {
    return listeningExercisesByLanguage.zh;
  }

  return listeningExercisesByLanguage[languageCode as SupportedListeningLanguageCode];
}

export function getListeningExercisesByType(languageCode: string | undefined, type: ListeningExerciseType): ListeningExercise[] {
  return getListeningExercisesByLanguage(languageCode).filter((exercise) => exercise.type === type);
}

type ListeningLessonBlueprint = {
  id: string;
  title: string;
  description: string;
  topicId: string;
  topicLabel: string;
  topicTitle: string;
  topicDescription: string;
};

const listeningLessonBlueprints: Record<ListeningExerciseType, ListeningLessonBlueprint[]> = {
  audio_choice: [
    {
      id: "audio-choice-dia-diem",
      title: "Bài 1 - Địa điểm quen thuộc",
      description: "Nghe và chọn địa điểm, nơi đến dễ cơ bản.",
      topicId: "audio-choice-giao-tiep",
      topicLabel: "GIAO TIẾP",
      topicTitle: "Tình huống giao tiếp cơ bản",
      topicDescription: "Làm quen với các mẫu nghe ngắn về địa điểm và nhu cầu hằng ngày.",
    },
    {
      id: "audio-choice-do-uong",
      title: "Bài 2 - Nhu cầu hằng ngày",
      description: "Tập nghe thông tin về đồ uống và sinh hoạt.",
      topicId: "audio-choice-giao-tiep",
      topicLabel: "GIAO TIẾP",
      topicTitle: "Tình huống giao tiếp cơ bản",
      topicDescription: "Làm quen với các mẫu nghe ngắn về địa điểm và nhu cầu hằng ngày.",
    },
    {
      id: "audio-choice-ke-hoach",
      title: "Bài 3 - Kế hoạch cuối tuần",
      description: "Nghe và nhận biết kế hoạch, hành động sắp tới.",
      topicId: "audio-choice-mo-rong",
      topicLabel: "MỞ RỘNG",
      topicTitle: "Nội dung mở rộng",
      topicDescription: "Tăng độ khó với các chủ đề về kế hoạch, môn học và quan điểm.",
    },
    {
      id: "audio-choice-quan-diem",
      title: "Bài 4 - Quan điểm học tập",
      description: "Nghe ý kiến và chọn thông tin đúng nhất.",
      topicId: "audio-choice-mo-rong",
      topicLabel: "MỞ RỘNG",
      topicTitle: "Nội dung mở rộng",
      topicDescription: "Tăng độ khó với các chủ đề về kế hoạch, môn học và quan điểm.",
    },
  ],
  audio_write: [
    {
      id: "audio-write-thoi-tiet",
      title: "Bài 1 - Thời tiết và hoạt động",
      description: "Nghe câu ngắn và viết lại nội dung chính xác.",
      topicId: "audio-write-nen-tang",
      topicLabel: "NỀN TẢNG",
      topicTitle: "Luyện nghe viết cơ bản",
      topicDescription: "Rèn nhịp nghe và ghi lại câu ngắn trong ngữ cảnh quen thuộc.",
    },
    {
      id: "audio-write-thoi-quen",
      title: "Bài 2 - Thói quen mỗi ngày",
      description: "Tập viết lại câu nói về thói quen học tập.",
      topicId: "audio-write-nen-tang",
      topicLabel: "NỀN TẢNG",
      topicTitle: "Luyện nghe viết cơ bản",
      topicDescription: "Rèn nhịp nghe và ghi lại câu ngắn trong ngữ cảnh quen thuộc.",
    },
    {
      id: "audio-write-di-chuyen",
      title: "Bài 3 - Di chuyển và lịch hẹn",
      description: "Nghe câu dài hơn về lịch trình, đón đưa và di chuyển.",
      topicId: "audio-write-ung-dung",
      topicLabel: "ỨNG DỤNG",
      topicTitle: "Tình huống ứng dụng",
      topicDescription: "Áp dụng nghe viết lại vào các câu có nhiều thành phần thông tin hơn.",
    },
    {
      id: "audio-write-y-dinh",
      title: "Bài 4 - Ý định và điều kiện",
      description: "Luyện viết lại câu có điều kiện và mục đích.",
      topicId: "audio-write-ung-dung",
      topicLabel: "ỨNG DỤNG",
      topicTitle: "Tình huống ứng dụng",
      topicDescription: "Áp dụng nghe viết lại vào các câu có nhiều thành phần thông tin hơn.",
    },
  ],
  video_choice: [
    {
      id: "video-choice-gia-dinh",
      title: "Bài 1 - Chủ đề gia đình",
      description: "Xem video ngắn và chọn chủ đề đúng.",
      topicId: "video-choice-doi-song",
      topicLabel: "ĐỜI SỐNG",
      topicTitle: "Video đời sống hằng ngày",
      topicDescription: "Làm quen với video ngắn về gia đình, trường học và sinh hoạt.",
    },
    {
      id: "video-choice-truong-hoc",
      title: "Bài 2 - Cuộc sống học đường",
      description: "Nhận diện thông tin trong video về học tập.",
      topicId: "video-choice-doi-song",
      topicLabel: "ĐỜI SỐNG",
      topicTitle: "Video đời sống hằng ngày",
      topicDescription: "Làm quen với video ngắn về gia đình, trường học và sinh hoạt.",
    },
    {
      id: "video-choice-du-lich",
      title: "Bài 3 - Kế hoạch du lịch",
      description: "Theo dõi video và chọn hành động sắp tới.",
      topicId: "video-choice-chu-de",
      topicLabel: "CHỦ ĐỀ",
      topicTitle: "Video theo chủ đề",
      topicDescription: "Tăng độ khó với nội dung du lịch, kỹ năng và cách làm.",
    },
    {
      id: "video-choice-ky-nang",
      title: "Bài 4 - Hướng dẫn kỹ năng",
      description: "Xem video hướng dẫn và xác định nội dung chính.",
      topicId: "video-choice-chu-de",
      topicLabel: "CHỦ ĐỀ",
      topicTitle: "Video theo chủ đề",
      topicDescription: "Tăng độ khó với nội dung du lịch, kỹ năng và cách làm.",
    },
  ],
};

function getListeningLessonBlueprint(type: ListeningExerciseType, index: number): ListeningLessonBlueprint {
  const blueprints = listeningLessonBlueprints[type];
  return (
    blueprints[index] ?? {
      id: `${type}-lesson-${index + 1}`,
      title: `Bài ${index + 1}`,
      description: "Bài luyện nghe.",
      topicId: `${type}-topic`,
      topicLabel: "CHỦ ĐỀ",
      topicTitle: "Chủ đề luyện nghe",
      topicDescription: "Danh sách bài luyện nghe.",
    }
  );
}

export function getListeningTopicsByType(languageCode: string | undefined, type: ListeningExerciseType): ListeningTopic[] {
  const lessonsByTopic = new Map<string, ListeningTopic>();

  getListeningExercisesByType(languageCode, type).forEach((exercise, index) => {
    const blueprint = getListeningLessonBlueprint(type, index);

    if (!lessonsByTopic.has(blueprint.topicId)) {
      lessonsByTopic.set(blueprint.topicId, {
        id: blueprint.topicId,
        label: blueprint.topicLabel,
        title: blueprint.topicTitle,
        description: blueprint.topicDescription,
        lessons: [],
      });
    }

    const topic = lessonsByTopic.get(blueprint.topicId);
    topic?.lessons.push({
      id: blueprint.id,
      title: blueprint.title,
      description: blueprint.description,
      exercises: [exercise],
    });
  });

  return Array.from(lessonsByTopic.values());
}

export function getListeningLessonById(
  languageCode: string | undefined,
  type: ListeningExerciseType,
  lessonId: string | undefined,
): ListeningLesson | null {
  if (!lessonId) {
    return null;
  }

  const topics = getListeningTopicsByType(languageCode, type);
  for (const topic of topics) {
    const lesson = topic.lessons.find((item) => item.id === lessonId);
    if (lesson) {
      return lesson;
    }
  }

  return null;
}

export function getListeningExercisesByLesson(
  languageCode: string | undefined,
  type: ListeningExerciseType,
  lessonId: string | undefined,
): ListeningExercise[] {
  return getListeningLessonById(languageCode, type, lessonId)?.exercises ?? [];
}
