import type { SupportedLanguageCode, WritingExercise, WritingExerciseMap } from "./types";

function createExercises(languageCode: SupportedLanguageCode, exercises: Omit<WritingExercise, "languageCode">[]): WritingExercise[] {
  return exercises.map((exercise) => ({
    ...exercise,
    languageCode,
  }));
}

export const writingExercisesByLanguage: WritingExerciseMap = {
  zh: createExercises("zh", [
    {
      id: "zh-1",
      type: "write_sentence",
      hanzi: "写一句环保句子",
      pinyin: "xiě yí jù huánbǎo jùzi",
      meaning: "Viet mot cau ve bao ve moi truong",
      answer: "我们应该保护环境。",
      hints: ["保护 (bǎohù) - bao ve", "环境 (huánjìng) - moi truong", "应该 (yīnggāi) - nen"],
      difficulty: "Cơ bản",
      explanation: "Cau mau: chu ngu + yinggai + dong tu + tan ngu.",
    },
    {
      id: "zh-2",
      type: "write_sentence",
      hanzi: "写一句关于学习中文的话",
      pinyin: "xiě yí jù guānyú xuéxí zhōngwén de huà",
      meaning: "Viết một câu về việc học tiếng Trung",
      answer: "我每天练习中文写作。",
      hints: ["每天 (měitiān) - mỗi ngày", "练习 (liànxí) - luyện tập", "写作 (xiězuò) - viết"],
      difficulty: "Cơ bản",
      explanation: "Co the nho mau: 我 + 时间 + 动词 + 宾语。",
    },
    {
      id: "zh-3",
      type: "write_sentence",
      hanzi: "写一句表达计划的话",
      pinyin: "xiě yí jù biǎodá jìhuà de huà",
      meaning: "Viet mot cau noi ve ke hoach",
      answer: "我下周要去上海出差。",
      hints: ["下周 (xià zhōu) - tuan sau", "要 (yào) - se", "出差 (chūchāi) - cong tac"],
      difficulty: "Trung cấp",
      explanation: "Moc thoi gian thuong dat truoc dong tu.",
    },
    {
      id: "zh-4",
      type: "type_by_meaning",
      hanzi: "请根据意思输入汉字",
      pinyin: "qǐng gēnjù yìsi shūrù hànzì",
      meaning: "Tôi muốn học tiếng Trung mỗi tối.",
      answer: "我每天晚上学中文。",
      hints: ["每天晚上 - mỗi tối", "学中文 - học tiếng Trung"],
      difficulty: "Cơ bản",
      explanation: "Thu tu tu nhien: 我 + 每天晚上 + 学 + 中文。",
    },
    {
      id: "zh-5",
      type: "type_by_meaning",
      hanzi: "请根据意思输入汉字",
      pinyin: "qǐng gēnjù yìsi shūrù hànzì",
      meaning: "Hôm nay trời rất đẹp.",
      answer: "今天天气很好。",
      hints: ["今天 - hom nay", "天气 - thoi tiet", "很好 - rat dep"],
      difficulty: "Cơ bản",
      explanation: "天气很好 la cum mo ta pho bien cho thoi tiet dep.",
    },
    {
      id: "zh-6",
      type: "type_by_meaning",
      hanzi: "请根据意思输入汉字",
      pinyin: "qǐng gēnjù yìsi shūrù hànzì",
      meaning: "Neu co thoi gian, toi se doc sach o nha.",
      answer: "如果有时间，我会在家看书。",
      hints: ["如果 - neu", "有时间 - co thoi gian", "看书 - doc sach"],
      difficulty: "Nâng cao",
      explanation: "Mẫu câu điều kiện: 如果...，我会...。",
    },
  ]),
  en: createExercises("en", [
    {
      id: "en-1",
      type: "write_sentence",
      hanzi: "Write one sentence about healthy habits",
      meaning: "Viet mot cau ve thoi quen lanh manh",
      answer: "I drink enough water every day.",
      hints: ["drink enough water", "every day", "healthy habit"],
      difficulty: "Cơ bản",
      explanation: "Cau nen co chu ngu + dong tu + bo ngu ro rang.",
    },
    {
      id: "en-2",
      type: "write_sentence",
      hanzi: "Write one sentence about your study routine",
      meaning: "Viet mot cau ve lich hoc cua ban",
      answer: "I review new words before going to bed.",
      hints: ["review new words", "before going to bed"],
      difficulty: "Cơ bản",
      explanation: "Dung cum before going to bed de chi thoi diem.",
    },
    {
      id: "en-3",
      type: "write_sentence",
      hanzi: "Write one sentence about future plans",
      meaning: "Viet mot cau ve ke hoach tuong lai",
      answer: "I will travel abroad to improve my English.",
      hints: ["will travel abroad", "improve my English"],
      difficulty: "Trung cấp",
      explanation: "Tuong lai don: will + dong tu nguyen mau.",
    },
    {
      id: "en-4",
      type: "type_by_meaning",
      hanzi: "Type the sentence in English",
      meaning: "Tôi học tiếng Anh với bạn bè mỗi cuối tuần.",
      answer: "I study English with my friends every weekend.",
      hints: ["study English", "with my friends", "every weekend"],
      difficulty: "Cơ bản",
      explanation: "Trang tu tan suat thuong dat cuoi cau trong mau nay.",
    },
    {
      id: "en-5",
      type: "type_by_meaning",
      hanzi: "Type the sentence in English",
      meaning: "Hôm nay tôi cần hoàn thành bài viết của mình.",
      answer: "I need to finish my writing task today.",
      hints: ["need to finish", "writing task", "today"],
      difficulty: "Trung cấp",
      explanation: "Need to + V là cấu trúc cần làm gì.",
    },
    {
      id: "en-6",
      type: "type_by_meaning",
      hanzi: "Type the sentence in English",
      meaning: "Nếu tôi luyện tập mỗi ngày, tôi sẽ tiến bộ nhanh hơn.",
      answer: "If I practice every day, I will improve faster.",
      hints: ["If I practice every day", "I will improve faster"],
      difficulty: "Nâng cao",
      explanation: "Mẫu câu điều kiện loại 1: If + hiện tại đơn, will + V.",
    },
  ]),
  ja: createExercises("ja", [
    {
      id: "ja-1",
      type: "write_sentence",
      hanzi: "環境について一文書いてください",
      meaning: "Viet mot cau ve moi truong",
      answer: "私たちは環境を守るべきです。",
      hints: ["環境 - kankyou", "守る - mamoru", "べきです - nen"],
      difficulty: "Cơ bản",
      explanation: "Mẫu câu: chủ ngữ + môi trường + động từ + beki desu.",
    },
    {
      id: "ja-2",
      type: "write_sentence",
      hanzi: "学習習慣について一文書いてください",
      meaning: "Viet mot cau ve thoi quen hoc tap",
      answer: "私は毎晩漢字を練習します。",
      hints: ["毎晩 - mỗi tối", "漢字 - kanji", "練習します - luyện tập"],
      difficulty: "Cơ bản",
      explanation: "Trang tu chi thoi gian thuong dat truoc tan ngu.",
    },
    {
      id: "ja-3",
      type: "write_sentence",
      hanzi: "将来の計画について一文書いてください",
      meaning: "Viet mot cau ve ke hoach tuong lai",
      answer: "来年日本で働きたいです。",
      hints: ["来年 - nam sau", "日本で - o Nhat", "働きたいです - muon lam viec"],
      difficulty: "Trung cấp",
      explanation: "たいです diễn đạt mong muốn của người nói.",
    },
    {
      id: "ja-4",
      type: "type_by_meaning",
      hanzi: "意味を見て日本語で入力してください",
      meaning: "Tôi học tiếng Nhật ở nhà mỗi ngày.",
      answer: "私は毎日家で日本語を勉強します。",
      hints: ["毎日 - mỗi ngày", "家で - ở nhà", "勉強します - học"],
      difficulty: "Cơ bản",
      explanation: "Tro tu を danh dau tan ngu, で danh dau dia diem hanh dong.",
    },
    {
      id: "ja-5",
      type: "type_by_meaning",
      hanzi: "意味を見て日本語で入力してください",
      meaning: "Hôm nay trời đẹp nên tôi muốn đi bộ.",
      answer: "今日は天気がいいので散歩したいです。",
      hints: ["今日は - hom nay", "天気がいい - troi dep", "散歩したい - muon di bo"],
      difficulty: "Trung cấp",
      explanation: "ので noi nguyen nhan va ket qua nhe hon kara.",
    },
    {
      id: "ja-6",
      type: "type_by_meaning",
      hanzi: "意味を見て日本語で入力してください",
      meaning: "Neu co thoi gian, toi se doc sach sau bua toi.",
      answer: "時間があれば、夕食の後で本を読みます。",
      hints: ["時間があれば - neu co thoi gian", "夕食の後で - sau bua toi", "本を読みます - doc sach"],
      difficulty: "Nâng cao",
      explanation: "〜あれば là dạng điều kiện phổ biến trong văn viết.",
    },
  ]),
  ko: createExercises("ko", [
    {
      id: "ko-1",
      type: "write_sentence",
      hanzi: "환경에 대한 문장을 하나 쓰세요",
      meaning: "Viet mot cau ve moi truong",
      answer: "우리는 환경을 보호해야 합니다.",
      hints: ["환경 - moi truong", "보호하다 - bao ve", "해야 합니다 - can / nen"],
      difficulty: "Cơ bản",
      explanation: "Cau truc: chu ngu + tan ngu + dong tu + haeya hamnida.",
    },
    {
      id: "ko-2",
      type: "write_sentence",
      hanzi: "공부 습관에 대한 문장을 하나 쓰세요",
      meaning: "Viet mot cau ve thoi quen hoc tap",
      answer: "저는 매일 밤 단어를 복습해요.",
      hints: ["매일 밤 - mỗi tối", "단어 - từ vựng", "복습해요 - ôn lại"],
      difficulty: "Cơ bản",
      explanation: "Mẫu câu nói thân mật với đuôi -해요.",
    },
    {
      id: "ko-3",
      type: "write_sentence",
      hanzi: "미래 계획에 대한 문장을 하나 쓰세요",
      meaning: "Viet mot cau ve ke hoach tuong lai",
      answer: "내년에 한국에서 일하고 싶어요.",
      hints: ["내년에 - nam sau", "한국에서 - o Han Quoc", "일하고 싶어요 - muon lam viec"],
      difficulty: "Trung cấp",
      explanation: "-고 싶어요 dung de dien dat mong muon.",
    },
    {
      id: "ko-4",
      type: "type_by_meaning",
      hanzi: "뜻을 보고 한국어로 입력하세요",
      meaning: "Tôi học tiếng Hàn ở nhà mỗi ngày.",
      answer: "저는 매일 집에서 한국어를 공부해요.",
      hints: ["매일 - mỗi ngày", "집에서 - ở nhà", "공부해요 - học"],
      difficulty: "Cơ bản",
      explanation: "-에서 danh dau noi xay ra hanh dong.",
    },
    {
      id: "ko-5",
      type: "type_by_meaning",
      hanzi: "뜻을 보고 한국어로 입력하세요",
      meaning: "Hôm nay trời đẹp nên tôi muốn đi dạo.",
      answer: "오늘 날씨가 좋아서 산책하고 싶어요.",
      hints: ["오늘 - hom nay", "날씨가 좋아서 - vi troi dep", "산책하고 싶어요 - muon di dao"],
      difficulty: "Trung cấp",
      explanation: "-아서/-어서 noi nguyen nhan tu nhien trong hoi thoai.",
    },
    {
      id: "ko-6",
      type: "type_by_meaning",
      hanzi: "뜻을 보고 한국어로 입력하세요",
      meaning: "Neu co thoi gian, toi se doc sach sau bua toi.",
      answer: "시간이 있으면 저녁 식사 후에 책을 읽을 거예요.",
      hints: ["시간이 있으면 - neu co thoi gian", "저녁 식사 후에 - sau bua toi", "책을 읽을 거예요 - se doc sach"],
      difficulty: "Nâng cao",
      explanation: "-으면 là cấu trúc điều kiện phổ biến trong tiếng Hàn.",
    },
  ]),
  de: createExercises("de", [
    {
      id: "de-1",
      type: "write_sentence",
      hanzi: "Schreibe einen Satz uber Umweltschutz",
      meaning: "Viet mot cau ve bao ve moi truong",
      answer: "Wir sollten die Umwelt schutzen.",
      hints: ["Wir sollten", "die Umwelt", "schutzen"],
      difficulty: "Cơ bản",
      explanation: "Modalverb sollten dung de dua ra loi khuyen.",
    },
    {
      id: "de-2",
      type: "write_sentence",
      hanzi: "Schreibe einen Satz uber deine Lernroutine",
      meaning: "Viet mot cau ve lich hoc cua ban",
      answer: "Ich wiederhole jeden Abend neue Worter.",
      hints: ["Ich wiederhole", "jeden Abend", "neue Worter"],
      difficulty: "Cơ bản",
      explanation: "Dong tu dung o vi tri thu hai trong cau khang dinh.",
    },
    {
      id: "de-3",
      type: "write_sentence",
      hanzi: "Schreibe einen Satz uber Zukunftsplane",
      meaning: "Viet mot cau ve ke hoach tuong lai",
      answer: "Nach dem Studium mochte ich in Deutschland arbeiten.",
      hints: ["Nach dem Studium", "mochte ich", "in Deutschland arbeiten"],
      difficulty: "Trung cấp",
      explanation: "Sau trang ngu o dau cau, dong tu chia dung o vi tri thu hai.",
    },
    {
      id: "de-4",
      type: "type_by_meaning",
      hanzi: "Tippe den Satz auf Deutsch",
      meaning: "Tôi học tiếng Đức ở nhà mỗi ngày.",
      answer: "Ich lerne jeden Tag zu Hause Deutsch.",
      hints: ["Ich lerne", "jeden Tag", "zu Hause", "Deutsch"],
      difficulty: "Cơ bản",
      explanation: "Trang ngu tan suat thuong dung truoc bo ngu dia diem.",
    },
    {
      id: "de-5",
      type: "type_by_meaning",
      hanzi: "Tippe den Satz auf Deutsch",
      meaning: "Hôm nay tôi cần hoàn thành bài viết của mình.",
      answer: "Ich muss heute meine Schreibaufgabe fertig machen.",
      hints: ["Ich muss", "heute", "meine Schreibaufgabe", "fertig machen"],
      difficulty: "Trung cấp",
      explanation: "Voi modalverb, dong tu nguyen mau dung cuoi cau.",
    },
    {
      id: "de-6",
      type: "type_by_meaning",
      hanzi: "Tippe den Satz auf Deutsch",
      meaning: "Nếu tôi luyện tập mỗi ngày, tôi sẽ tiến bộ nhanh hơn.",
      answer: "Wenn ich jeden Tag ube, werde ich schneller besser.",
      hints: ["Wenn ich jeden Tag ube", "werde ich", "schneller besser"],
      difficulty: "Nâng cao",
      explanation: "Menh de voi Wenn day dong tu chia xuong cuoi menh de.",
    },
  ]),
};

export function getWritingExercisesByLanguage(languageCode: string | undefined): WritingExercise[] {
  if (!languageCode || !(languageCode in writingExercisesByLanguage)) {
    return writingExercisesByLanguage.zh;
  }

  return writingExercisesByLanguage[languageCode as SupportedLanguageCode];
}
